# Generated by Django 5.1 on 2024-09-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='breed',
            new_name='edad',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='age',
        ),
        migrations.AddField(
            model_name='pet',
            name='imagen',
            field=models.CharField(default='default_image.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='pet',
            name='size',
            field=models.CharField(default='No especificado', max_length=100),
        ),
        migrations.AddField(
            model_name='pet',
            name='ubicacion',
            field=models.CharField(default='No especificado', max_length=100),
        ),
    ]
