# Generated by Django 5.1 on 2024-09-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pet_sexo_alter_pet_edad_alter_pet_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='edad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='imagen',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sexo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(default='No especificado', max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='ubicacion',
            field=models.CharField(max_length=100),
        ),
    ]
