# Generated by Django 5.1 on 2024-09-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_pet_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='tipo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
