# Generated by Django 5.1 on 2024-10-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nombre',
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='form_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
